### ISSUE TITLE
what is this supposed to do?

### ISSUE THREAD

**Issue by shoshanatech** [ionic-team/ionic-intro#2]
The readme says it enables an intro tutorial, but all I see is controllers, services and templates for a petshop app.

**Comment by peterbenoit** [comment]
Good question!

**Comment by adamdbradley** [comment]
Greetings @shoshanatech!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
